<?php

namespace PortalBundle\Repository;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends \Doctrine\ORM\EntityRepository
{
}
